using CognitiveServices.Models.Reports;
using System;
using System.Collections.Generic;
using System.Text;

namespace CognitiveServices
{
    public static class ApiEndpoints
    {
        public const string AZURE_BASE_URL_TEMPLATE = "https://{0}.api.cognitive.microsoft.com/";
        public const string WEB_SEARCH_URL = "https://api.cognitive.microsoft.com/bingcustomsearch/v7.0/search?";
        public const string IMAGE_SEARCH_URL = "https://api.cognitive.microsoft.com/bingcustomsearch/v7.0/images/search?";
        public const string VIDEO_SEARCH_URL = "https://api.cognitive.microsoft.com/bingcustomsearch/v7.0/videos/search?";
        public const string AUTOSUGGEST_URL = "https://api.cognitive.microsoft.com/bingcustomsearch/v7.0/suggestions/search?";
        public const string VISUAL_SEARCH_URL = "https://api.cognitive.microsoft.com/bing/v7.0/images/visualsearch?";
        public const string TEXT_ANALYTICS_LANGUAGE_URL = "https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/languages";
        public const string TEXT_ANALYTICS_KEYPHRASES_URL = "https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/keyPhrases";
        public const string TEXT_ANALYTICS_SENTIMENT_URL = "https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/sentiment";
        public const string TEXT_ANALYTICS_ENTITY_URL = "https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/entities";
        public const string CONTENT_MODERATOR_SCREEN_URL = "https://eastus.api.cognitive.microsoft.com/contentmoderator/moderate/v1.0/ProcessText/Screen?";
        public const string CONTENT_MODERATOR_EVALUATE_URL = "https://eastus.api.cognitive.microsoft.com/contentmoderator/moderate/v1.0/ProcessImage/Evaluate?";
    }

    public static class ReviewLibrary
    {
        public static IEnumerable<Review> Reviews = new List<Review>
        {
            new Review { ReviewHeadline = "Five Stars", ReviewBody = "Excellent!!!", StarRating = 5, Sentiment = 0.97, Language = "English", LanguageConfidence = 1, KeyPhrases = "" },
new Review { ReviewHeadline = "Good quality track at excellent price", ReviewBody = "Great quality wooden track (better than some others we have tried). Perfect match to the various vintages of Thomas track that we already have. There is enough track here to have fun and get creative incorporating your key pieces with track splits, loops and bends.", StarRating = 5, Sentiment = 0.96, Language = "English", LanguageConfidence = 1, KeyPhrases = "track splits, Great quality wooden track, key pieces, loops, various vintages of Thomas, Perfect match, fun, bends" },
new Review { ReviewHeadline = "Two Stars", ReviewBody = "Cards are not as big as pictured.", StarRating = 2, Sentiment = 0.2572, Language = "English", LanguageConfidence = 1, KeyPhrases = "Cards" },
new Review { ReviewHeadline = "my daughter loved it and i liked the price and it came ...", ReviewBody = "my daughter loved it and i liked the price and it came to me rather than shopping with a ton of people around me. Amazon is the Best way to shop!", StarRating = 5, Sentiment = 0.96, Language = "English", LanguageConfidence = 1, KeyPhrases = "Amazon, Best way, shopping, ton of people, daughter, price" },
new Review { ReviewHeadline = "DONT BUY THESE!", ReviewBody = "Do not buy these! They break very fast I spun then for 15 minutes and the end flew off don't waste your money. They are made from cheap plastic and have cracks in them. Buy the poi balls they work a lot better if you only have limited funds.", StarRating = 1, Sentiment = 0.11, Language = "English", LanguageConfidence = 1, KeyPhrases = "lot better, poi balls, end, cracks, cheap plastic, minutes, money, funds" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Great item. Pictures pop thru and add detail as &#34;painted.&#34;  Pictures dry and it can be repainted.", StarRating = 5, Sentiment = 0.96, Language = "English", LanguageConfidence = 1, KeyPhrases = "Pictures pop, Pictures dry, Great item" },
new Review { ReviewHeadline = "Three Stars", ReviewBody = "To keep together, had to use crazy  glue.", StarRating = 3, Sentiment = 0.2, Language = "English", LanguageConfidence = 1, KeyPhrases = "crazy glue" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "I was pleased with the product.", StarRating = 5, Sentiment = 0.91, Language = "English", LanguageConfidence = 1, KeyPhrases = "product" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Children like it", StarRating = 5, Sentiment = 0.92, Language = "English", LanguageConfidence = 1, KeyPhrases = "Children" },
new Review { ReviewHeadline = "Shame on the seller !!!", ReviewBody = "Showed up not how it's shown . Was someone's old toy. with paint on it.", StarRating = 1, Sentiment = 0.8, Language = "English", LanguageConfidence = 1, KeyPhrases = "old toy, paint" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Really liked these. They were a little larger than I thought, but still fun.", StarRating = 5, Sentiment = 0.95, Language = "English", LanguageConfidence = 1, KeyPhrases = "" },
new Review { ReviewHeadline = "Nice huge balloon", ReviewBody = "Nice huge balloon! Had my local grocery store fill it up for a very small fee, it was totally worth it!", StarRating = 5, Sentiment = 0.94, Language = "English", LanguageConfidence = 1, KeyPhrases = "Nice huge balloon, local grocery store, small fee" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Great deal", StarRating = 5, Sentiment = 0.97, Language = "English", LanguageConfidence = 1, KeyPhrases = "Great deal" },
new Review { ReviewHeadline = "Four Stars", ReviewBody = "As Advertised", StarRating = 4, Sentiment = 0.22, Language = "English", LanguageConfidence = 1, KeyPhrases = "" },
new Review { ReviewHeadline = "... servo so expect to spend 150 more on a good servo immediately be the stock one breaks right", ReviewBody = "Comes w a 15$ servo so expect to spend 150 more on a good servo immediately be the stock one breaks right away", StarRating = 3, Sentiment = 0.23, Language = "English", LanguageConfidence = 1, KeyPhrases = "good servo, stock, breaks" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "awesome ! Thanks!", StarRating = 5, Sentiment = 1, Language = "English", LanguageConfidence = 1, KeyPhrases = "Thanks" },
new Review { ReviewHeadline = "The closest relevance I have to items like these is while in the army I was trained ...", ReviewBody = "I got this item for me and my son to play around with. The closest relevance I have to items like these is while in the army I was trained in the camera rc bots. This thing is awesome we tested the range and got somewhere close to 50 yards without an issue. Getting the controls is a bit tricky at first but after about twenty minutes you get the feel for it. The drone comes just about fly ready you just have to sync the controller. I am definitely a fan of the drones now. Only concern I have is maybe a little more silent but other than that great buy.<br /><br />*Disclaimer I received this product at a discount for my unbiased review.", StarRating = 5, Sentiment = 0.79, Language = "English", LanguageConfidence = 1, KeyPhrases = "range, discount, product, great buy, unbiased review, camera rc bots, thing, yards, issue, Disclaimer, controls, minutes, item, son, closest relevance, feel, fan, drones, army, controller" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "It was a birthday present for my grandson and he LOVES IT!!", StarRating = 5, Sentiment = 0.95, Language = "English", LanguageConfidence = 1, KeyPhrases = "birthday present, grandson" },
new Review { ReviewHeadline = "Got wrong product in the shipment", ReviewBody = "Got a wrong product from Amazon Vine and unable to provide a good review. We received a pair of cute girls gloves and a baseball ball instead, while we were expecting a boys batting tee. The gloves are cute, however made for at least 6+ yrs or above...more likely 8-9 yrs old girls.<br /><br />Can't provide a fair review as we were not able to use the product.", StarRating = 3, Sentiment = 0.86, Language = "English", LanguageConfidence = 1, KeyPhrases = "gloves, yrs old girls, pair of cute girls, wrong product, good review, fair review, Amazon Vine, baseball ball, boys, tee" },
new Review { ReviewHeadline = "Overpriced.", ReviewBody = "You need expansion packs 3-5 if you want access to the player aids for the Factions expansion. The base game of Alien Frontiers just plays so much smoother than adding Factions with the expansion packs. All this will do is pigeonhole you into a certain path to victory.", StarRating = 1, Sentiment = 0.25, Language = "English", LanguageConfidence = 1, KeyPhrases = "Factions expansion, expansion packs, player aids, base game of Alien Frontiers, certain path, victory, access" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Awesome customer service and a cool little drone! Especially for the price!", StarRating = 5, Sentiment = 1, Language = "English", LanguageConfidence = 1, KeyPhrases = "cool little drone, Awesome customer service, price" },
new Review { ReviewHeadline = "Great product for little girls!", ReviewBody = "I got these for my daughters for plane trip. I liked that the zipper pouch was attached for markers.  However, that pouch fell off.  But the girls have loved coloring their own stickers. Would def buy this again.", StarRating = 4, Sentiment = 0.85, Language = "English", LanguageConfidence = 1, KeyPhrases = "zipper pouch, daughters, plane trip, girls, coloring, stickers, markers" },
new Review { ReviewHeadline = "Creative and fun!", ReviewBody = "My girlfriend and I are both into yoga and I gave her a set of the Yoga Joes for her new home yoga room. When she saw them, she was impressed that I had found little green army men like her brother used to play with. Then she realized they were doing yoga and she almost exploded with delight. You should have seen the look on her face. Needless to say, the gift was a huge hit. They are absolutely brilliant!", StarRating = 5, Sentiment = 0.85, Language = "English", LanguageConfidence = 1, KeyPhrases = "Yoga Joes, new home yoga room, little green army men, brother, gift, set, huge hit, look, face, girlfriend, delight" },
new Review { ReviewHeadline = "i like it but i absoloutely hate that some dolls don't ...", ReviewBody = "i like it but i absoloutely hate that some dolls don't have pets like this one so I'm not stoked and i really would have liked to see her pet", StarRating = 4, Sentiment = 0.24, Language = "English", LanguageConfidence = 1, KeyPhrases = "dolls, absoloutely hate, pets" },
new Review { ReviewHeadline = "We love how well they are made", ReviewBody = "We have MANY Wow toys in our home.  We love how well they are made.  The advent calendar is an exception.  The plastic is thinner than our other wow toys and the barn animals won't even stand up on their own due to the head weighing more than the body and uneven base of the toy.  Very disappointing when we love the concept.  The story to read along with everyday is great.  I would have preferred quality (and would have paid more for it) instead of a cheap &#34;knock-off&#34; of the rest of their toy line.  It is very obvious by the weight of the toys sloppy paint jobs which items in our &#34;Wow Toys&#34; bin are part advent calendar vs. the rest of the toys we have.  Also there is a lot of overlap between the wow town advent calendar & winter wonderland calendar, which makes me want to look for alternatives for this year's advent calendar options.", StarRating = 3, Sentiment = 0.79, Language = "English", LanguageConfidence = 1, KeyPhrases = "Wow toys, wow town advent calendar, year's advent calendar options, winter wonderland calendar, toys sloppy paint jobs, rest, toy line, weight, body, items, alternatives, lot of overlap, bin, uneven base, barn animals, plastic, home, exception, concept, preferred quality, knock, story, head" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Tons of fun", StarRating = 5, Sentiment = 0.92, Language = "English", LanguageConfidence = 1, KeyPhrases = "Tons of fun" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Love it great add to collecton", StarRating = 5, Sentiment = 1, Language = "English", LanguageConfidence = 1, KeyPhrases = "collecton" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Exactly as described.  Fits my 7-yr old well!", StarRating = 5, Sentiment = 0.86, Language = "English", LanguageConfidence = 1, KeyPhrases = "yr old" },
new Review { ReviewHeadline = "The children LOVED them and best part was that it helped the ...", ReviewBody = "Purchased these Lego's to help aid me with teaching my Sunday School class. The children LOVED them and best part was that it helped the children remember past lessons. The true Lego brand seem to work/snap together/fit together better than the generic brands. (Plus I had some Lego snobs in my class that only would use the real Lego brand and shunned the generic brand). Only wish Lego's were a little cheaper but you get what you pay for and I would recommend for quality to purchase this set.", StarRating = 5, Sentiment = 0.25, Language = "English", LanguageConfidence = 1, KeyPhrases = "real Lego brand, true Lego brand, Lego snobs, children, Lego's, generic brands, School class, past lessons, snap, quality, set" },
new Review { ReviewHeadline = "My little dog can bite my hand right through the puupet.", ReviewBody = "IT's OK, but not as good as the old Bite Meez puppets. This puppet is very thin. My little yorkie often bites my hands right through the stuffing. It not durable enough to really play with.", StarRating = 2, Sentiment = 0.11, Language = "English", LanguageConfidence = 1, KeyPhrases = "old Bite Meez puppets, hands, little yorkie, stuffing" },
new Review { ReviewHeadline = "Save your money...don't buy!", ReviewBody = "This was to be a gift for my husband for our new pool. Did not receive the color I ordered but most of all after only one month of use (not continuously) the mesh pulled away from the material and the inflatable side. Completely shredded and no longer of use. It was stored properly and was not kept outside or in the pool. Poorly made, better off going to W**-M*** and getting something on clearance.", StarRating = 1, Sentiment = 0.7, Language = "English", LanguageConfidence = 1, KeyPhrases = "new pool, month of use, husband, material, gift, mesh, color, clearance" },
new Review { ReviewHeadline = "but I've bought one in the past and loved", ReviewBody = "Ended up sending this guy back because I didnt need it, but I've bought one in the past and loved it", StarRating = 5, Sentiment = 0.81, Language = "English", LanguageConfidence = 1, KeyPhrases = "guy, didnt" },
new Review { ReviewHeadline = "Three Stars", ReviewBody = "The product is good, but the box was broken.", StarRating = 3, Sentiment = 0.14, Language = "English", LanguageConfidence = 1, KeyPhrases = "product, box" },
new Review { ReviewHeadline = "CAN SAVE TME IF YOU UNDESTAND HOW IT WORKS .", ReviewBody = "Works well ,quality product but this style of board will charge multiple batteries at the same time SAFELY  ( IF )  ALL BATTERIES ARE OF THE SAME CELL COUNT , THE SAME BATTERY COMPOSITION ( LIPO, NIMH-etc ) AND THEY MUST HAVE INDIVIDUAL CELL VOLTAGES THAT ARE VERY CLOSE AND EQUAL TO EACH BATTERY CONNECTED AT THE SAME TIME . When board is connected to most if not all chargers it can only read total and individual cell voltage of ONE OF THE BATTERIES AND MAY OVER OR UNDER CHARGE THE OTHERS TO SOME DEGREE , TOTAL RATE OF CHARGE IS DIVIDED EQUALLY BETWEEN BATTERIES CONNECTED AT THE SAME TIME . Close monitoring is a must  when using like all high discharge batteies . I  have only personally expeienced one lipo battery meltdown and it is a very  SHORT IF NOT  NON EXISTANT WINDOW OF OPPERUNITY TO PREVENT OR MINIMISE THE COLATTERAL DAMAGE ONCE THE PROCESS STARTS . Read and understand all charging and battery instructions .", StarRating = 5, Sentiment = 0.1, Language = "English", LanguageConfidence = 1, KeyPhrases = "time, BATTERY COMPOSITION, multiple batteries, battery instructions, lipo battery meltdown, CELL COUNT, INDIVIDUAL CELL VOLTAGES, TOTAL RATE OF CHARGE, style of board, Close monitoring, DEGREE, EXISTANT WINDOW OF OPPERUNITY, quality product, NIMH, COLATTERAL DAMAGE, high discharge batteies, PROCESS, charging, chargers" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "Great gift!", StarRating = 5, Sentiment = 0.97, Language = "English", LanguageConfidence = 1, KeyPhrases = "Great gift" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "We play this game quite a bit with friends.", StarRating = 5, Sentiment = 0.83, Language = "English", LanguageConfidence = 1, KeyPhrases = "game, friends" },
new Review { ReviewHeadline = "BCW - Deluxe Currency Slab", ReviewBody = "Fits my $20 bill perfectly.", StarRating = 5, Sentiment = 0.89, Language = "English", LanguageConfidence = 1, KeyPhrases = "bill" },
new Review { ReviewHeadline = "Fun for birthday party favor", ReviewBody = "I ordered these for my 3 year old son's birthday party as party favors. They were a huge hit & the perfect fit for a 3 year old!", StarRating = 5, Sentiment = 0.88, Language = "English", LanguageConfidence = 1, KeyPhrases = "year old son's birthday party, party favors, perfect fit, huge hit" },
new Review { ReviewHeadline = "Love the prints!", ReviewBody = "These paper lanterns are adorable! The colors are bright, the patterns are fun & trendy & they're a good size! They came well packaged & are easy to assemble, they're also really easy to take apart & flatten back down! We'll get to use them for a few Halloweens I'm sure! They even came with the string needed to hang! I'm glad I grabbed them, they're really cute, my kids are excited to add to the Halloween decor & are already asking to hang them!<br />I received this item at a discount for my unbiased review.", StarRating = 5, Sentiment = 0.97, Language = "English", LanguageConfidence = 1, KeyPhrases = "patterns, item, discount, unbiased review, good size, paper lanterns, kids, Halloween decor, colors, Halloweens, string" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "My Grandson loves these cards.  Thank you", StarRating = 5, Sentiment = 0.96, Language = "English", LanguageConfidence = 1, KeyPhrases = "Grandson, cards" },
new Review { ReviewHeadline = "One Star", ReviewBody = "Received a pineapple rather than the advertised s'more", StarRating = 1, Sentiment = 0.75, Language = "English", LanguageConfidence = 1, KeyPhrases = "pineapple, advertised s'more" },
new Review { ReviewHeadline = "Four Stars", ReviewBody = "Christmas gift for 6yr", StarRating = 4, Sentiment = 0.77, Language = "English", LanguageConfidence = 1, KeyPhrases = "Christmas gift" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "My Grandson loves these cards.  Thank you", StarRating = 5, Sentiment = 0.96, Language = "English", LanguageConfidence = 1, KeyPhrases = "Grandson, cards" },
new Review { ReviewHeadline = "they LOVE this game", ReviewBody = "Even though both of my kids are at the top of this age recommendation level, they LOVE this game!  I love how it caters to the kinesthetic learner by asking them to move their bodies into the shape of the letters.  It even takes teamwork as sometimes two people are required to finish the letter.  My kids know all of their letter sounds and shapes, but this didn't stop them from playing the game over and over.", StarRating = 5, Sentiment = 0.78, Language = "English", LanguageConfidence = 1, KeyPhrases = "game, kids, age recommendation level, bodies, letters, people, kinesthetic learner, teamwork, shapes" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "My 5 year old son loves this.", StarRating = 5, Sentiment = 0.93, Language = "English", LanguageConfidence = 1, KeyPhrases = "year old son" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "love it", StarRating = 5, Sentiment = 0.99, Language = "English", LanguageConfidence = 1, KeyPhrases = "" },
new Review { ReviewHeadline = "Absolutely one of the best traps in the game", ReviewBody = "Absolutely one of the best traps in the game. It is never a dead and always live since you can always pay half your lifepoints for its cost. It's main power is that it can stop any card. Hopefully this card comes off the Forbidden/Limited list soon.", StarRating = 5, Sentiment = 0.18, Language = "English", LanguageConfidence = 1, KeyPhrases = "card, Limited list, best traps, game, main power, lifepoints, cost" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "really soft and cute", StarRating = 5, Sentiment = 0.88, Language = "English", LanguageConfidence = 1, KeyPhrases = "" },
new Review { ReviewHeadline = "Five Stars", ReviewBody = "baby loved it - so attractive and very nice", StarRating = 5, Sentiment = 1, Language = "English", LanguageConfidence = 1, KeyPhrases = "baby" },

        };
    }
}
